### ISSUE TITLE
Lore via .split?

### ISSUE THREAD

**Issue by avanrider** [27rogi/ColorfulAnvils#1]
I'm working on a fork, and have very little Java knowledge (javascript background).
I'm trying to figure out how to update the lore using the string split() function, so players can add custom lore to an item via the anvil interface.

While I can call split the name into an array, where I'm lost is how to then take the 2nd item in the array and assign it as lore. 
So... consider this a feature request? Something of a middle ground between this and renameIt!

**Comment by 27rogi** [comment]
I don't think it's a good idea to use anvil interface with limited string size to apply name and lore at the same time.

About your problem. `split` works the same in Java, all you need to do for your idea is to assign first string in the array to item's name and then assign all other lines to the item's lore. You can check my code to see how lore is added: https://github.com/rogi27/RenameIt/blob/1.19/src/main/java/space/rogi27/renameit/commands/LoreCommand.java#L29
